### ISSUE TITLE
Not compatible with ASP.Net Core 3.0

### ISSUE THREAD

**Issue by MarcusWichelmann** [FubarDevelopment/WebDavServer#51]
As you probably already know, the current stable version is not usable together with ASP.Net Core 3.0.

I'm talking about this error which appeared after a (necessary) update to 3.0 because of the deprecated empty constructor for `XmlSerializerInputFormatter`:
```
Unhandled exception. System.MissingMethodException: Method not found: 'Void Microsoft.AspNetCore.Mvc.Formatters.XmlSerializerInputFormatter..ctor()'.
   at FubarDev.WebDavServer.AspNetCore.Formatters.WebDavXmlSerializerInputFormatter..ctor()
   at FubarDev.WebDavServer.AspNetCore.Formatters.Internal.WebDavXmlSerializerMvcOptionsSetup.Configure(MvcOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.<>c.<AddMvcCoreServices>b__5_0(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
...
```

You have already fixed this issue in your `release/2.0` branch, which is great:
https://github.com/FubarDevelopment/WebDavServer/blob/release/2.0/src/FubarDev.WebDavServer.AspNetCore/Formatters/WebDavXmlSerializerInputFormatter.cs#L20

But I'm still wondering how to proceed with using this library with 3.0 now. Is your `release/2.0` branch stable enough for production usage? Are there any NuGet packages available for it?

In case the `release/2.0` branch shouldn't be used yet: What do you think about backporting the most essential fixes (like the above mentioned) to `master` and releasing them? This would prevent any application which uses this library from breaking after the 3.0 update.

**Comment by fubar-coder** [comment]
The 2.0 branch should be stable. A backport would be difficult as it would be a breaking change. There aren't much breaking changes (if any at all). It is mostly a feature update. I have to take a look at the current state of the branch and will give you a definitive answer soon.

**Comment by MarcusWichelmann** [comment]
Awesome. Could you consider publishing a prerelease package like `2.0-alpha1` for now please? This would be a huge help. :smile:

**Comment by MarcusWichelmann** [comment]
Wow, nice work! :smile:
_Just scrolled through that..._

**Comment by fubar-coder** [comment]
@MarcusWichelmann You may try the following NuGet feed:

https://pkgs.dev.azure.com/fubar-development/webdav-server/_packaging/webdav-server/nuget/v3/index.json

It's not stable yet, but I'm working on it.

**Comment by MarcusWichelmann** [comment]
Thanks, that's looking good.
But for now I need to stay in my `controller-url-fix` branch until it gets merged.

**Comment by MarcusWichelmann** [comment]
Okay, that was fast. I'll switch. :joy:

**Comment by MarcusWichelmann** [comment]
Works like a charm :+1:

**Comment by fubar-coder** [comment]
Please upgrade to 2.0.0-beta.81. It handles file names like `test%201.txt` too. Please close this issue when all your path-related issues are fixed too.

**Comment by MarcusWichelmann** [comment]
@fubar-coder Cool. It's getting better now. I can create a directory with `%20` in the name now and can list its contents, but when copying a file into it I get a `409 Conflict` with following message:
```C#
dbug: FubarDev.WebDavServer.Handlers.Impl.CopyHandler[0]
      => ConnectionId:0HLQPF58BVJQC => RequestPath:/Mein%20Benutzerordner/some-file.pdf RequestId:0HLQPF58BVJQC:0000000A, SpanId:|f060ac58-4b511e94944b4713., TraceId:f060ac58-4b511e94944b4713, ParentId: => Magis.School.Server.Controllers.WebDavController.CopyAsync (Magis.School.Server)
      Mein%20Benutzerordner/Test%2520keks/some-file.pdf: The target is missing with the following path parts: Mein%20Benutzerordner, Test%2520keks, some-file.pdf
```

**Comment by fubar-coder** [comment]
Ok, I'll take a look

**Comment by fubar-coder** [comment]
Version 2.0.0-beta.91 is released which fixes the problems around copying/moving to/from directories with spaces.

**Comment by MarcusWichelmann** [comment]
Seems to work fine, at least I cannot get it to break anymore. I tried with my web client as well as gvfs. :+1:
